import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="es">
      {/* 2. Le agregamos 'flex flex-col min-h-screen' al body para la estructura */}
      <body className="antialiased bg-white text-gray-900 flex flex-col min-h-screen">
        
        {/* Navbar Global */}
        <nav className="bg-white border-b border-gray-100 py-4 px-8 sticky top-0 z-50">
          <div className="max-w-6xl mx-auto flex justify-between items-center">
            <Link href="/" className="text-2xl font-extrabold tracking-widest text-black uppercase">
              Joyería
            </Link>
            <div className="space-x-6">
              <Link href="/" className="text-gray-600 hover:text-black font-medium transition-colors">Inicio</Link>
              <Link href="/catalogo" className="text-gray-600 hover:text-black font-medium transition-colors">Catálogo</Link>
            </div>
          </div>
        </nav>

        {/* 3. Envolvemos el children en un main con 'flex-grow' para empujar el Footer hacia abajo */}
        <main className="flex-grow">
          {children}
        </main>

        {/* 4. Colocamos el Footer justo antes de cerrar el body */}
        <Footer />
        
      </body>
    </html>
  );
}
